config/routes.rb
Rails.application.routes.draw do
  root "blogs#index"
  resources :users, only:[:index,:create,:new]
  resources :sessions, only: [:create]
  resources :blogs
  get "log_out"=>"sessions#destroy"
  post "filter"=>"blogs#filter"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogg.rb
class Blogg < ApplicationRecord
  belongs_to :user
  validates :blog_name,:blog,:blog_genre , presence: true
  
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bloggs
  has_secure_password
  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :email, presence: true
  validates :email ,format: {with:VALID_EMAIL_REGEX},uniqueness:{:case_sensitive=>false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

def current_user
if session[:user_id]
    return User.find(session[:user_id])
end
end
def require_login
    unless session[:user_id]
flash[:errors]=["You must login first"]
redirect_to users_path       
    end
end

def isLoggedin
    if session[:user_id]
        redirect_to blogs_url
    end
end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :require_login, :except => [:index]

    def index

    if session[:user_id]
    @user = User.find(session[:user_id])
    end
    if params[:filter_genre]
    @blogs =Blogg.where(blog_genre:params[:filter_genre])  
    else 
        @blogs=Blogg.order('created_at DESC')

    end

    @genres=["Fashion","Travel","Music","Lifestyle","Fitness","Sports","Parenting","Food","DIY"]
   
    end

    def new 
    @user=User.find(session[:user_id])
    @blog=Blogg.new 
    @genres=["Fashion","Travel","Music","Lifestyle","Fitness","Sports","Parenting","Food","DIY"]
    end


    def create
    blog=Blogg.new(blog_params)
    if blog.save 
    redirect_to root_path
    else
        flash[:errors]=blog.errors.full_messages
        redirect_back(fallback_location: root_path)
    end
    end

private
    def blog_params
        params.require(:blog).permit(:blog_name,:blog,:blog_genre,:user_id)
    end

    def filter_params
        params.permit(:filter_genre)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
      user=User.find_by(email:params[:email])
      if user && user.authenticate(params[:password])
      session[:user_id]=user.id
      redirect_to blogs_url
      else
        flash[:errors]=[]
        if params[:email] ==""
          flash[:errors]=flash[:errors].push("Email field is empty")

        end
        if params[:password]==""
         
          flash[:errors]=flash[:errors].push("Password field is empty")

        end


        flash[:errors] =flash[:errors].push("Invalid Combination") 

        redirect_to root_path
      end
    end
def destroy
reset_session
redirect_to root_path
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :isLoggedin, only: [:index]

def index
@user=User.new
end

def create
user=User.new(user_params)
if user.save
    redirect_to users_path
else
    flash[:errors]= user.errors.full_messages
    redirect_to action: "new"
end
end
def new

end

private
def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation);   
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/blogs/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light pb-0">
  <a class="navbar-brand" href="#"> <%= image_tag 'logo',style:'width:60px' %> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
    <%= link_to "Home",root_path,:class=>'nav-link' %>         </li>
     
        <li class="nav-item">
     <%= link_to "New Blog",new_blog_path,:class=>'nav-link' %>    
    
      </li>
 
    </ul>
    <span class="navbar-text">
    <% if @user %>
     <span>Currently Logged in as <%= @user.name %></span>
    </span>
    <div class="navbar-text">
<%= link_to "Log Out", "/log_out", class: "btn btn-warning btn-sm ml-3" %>
    </div>
  </div>
  <%end %>
</nav>

app/views/blogs/index.html.erb
<%= render :partial => 'nav', :object => @user %>

<div class="container-fluid c2">
<% if @blogs.length == 0 %>
<h1 class="mt-5">There are no blogs in this category :/</h1>
<% end %>
<div class="row mt-5 ml-2">
<%= form_tag({controller: "blogs", action: "index"}, {:method=>"get"}) do %>
 <%= select_tag "filter_genre", raw("<option>Select a Genre</option><option>Fashion</option><option>Music</option><option>Travel</option><option>Lifestyle</option><option>Sports</option><option>Fitness</option><option>DIY</option><option>Food</option><option>Parenting</option>"),class:'form-control sg'
 %>
  <%= submit_tag("Filter by Category",class:'btn btn-secondary mt-2') %>
<% end %>
</div>
<% if @blogs.length>0%>
<h1 class="mt-5">All Recent Blogs </h1>
<% end %>
<% @blogs.each do |b|%>
<div class="row flex-column ml-1 blog mb-2">
<h3><%= b.blog_name %> <h6>By <b><%= b.user.email %></b> <%= b.created_at.strftime("%d-%b-%Y, %I:%M %p") %></h6></h3> <h6><%= b.blog_genre %> Category</h6>
<div><%= b.blog %></div>
</div>
<% end %>
</div>

app/views/blogs/new.html.erb
<%= render :partial => 'nav', :object => @user %>
<div class="container-fluid c2 mid">
<div >
 <% if flash[:errors] %>
<% flash[:errors].each do |e| %>
<p class="text-danger"><%= e %></p>
 <% end %>
  <% end %>
</div>
<div class="row">
<%= form_for @blog,url: blogs_path(@blog),html: { class: "form-group" } do |f| %>
<input type="hidden" name="blogg[user_id]" value=<%= @user.id %>>

  <%= f.text_field :blog_name,class: "form-control",placeholder:"Blog Name"  %><br />
  <%= collection_select(:blogg, :blog_genre, @genres,:to_s,:to_s, {:include_blank => "Please select a Blog Genre"},class:'form-control')
 %>
  <%= f.text_area :blog,size: "60x12",class: "form-control mt-4",placeholder:"Blog .."  %><br />
  <%= f.submit "Create Blog", class:'btn btn-warning' %>
<% end %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="container c1">

<%= image_tag 'logo' %>
 <% if flash[:errors] %>
<% flash[:errors].each do |e| %>
<p class="text-danger"><%= e %></p>
 <% end %>
  <% end %>
<%= form_tag sessions_path do %>
<div class="form-group">
 <%= label_tag :email %>
 <%= email_field_tag :email ,nil,{:class=>'form-control'} %>

</div>
<div class="form-group">
 <%= label_tag :password  %>
 <%= password_field_tag :password ,nil,{:class=>'form-control'} %>
 
</div>
<%= submit_tag "Sign In",:class=>'form-control btn btn-primary' %>
<%= link_to "Register", { :controller => :users, :action => :new }, { class: "form-control btn btn-primary mt-2" } %>

<% end %>
</div>

app/views/users/new.html.erb
<div class="container c1">

<%= image_tag 'logo' %>
<% if flash[:errors] %>
<% flash[:errors].each do |e|%>
<p class="text-danger"><%= e %></p>
<% end %>
<% end %>
<%= form_for User.new do |f| %>
<div class="form-group">
 <%= f.label :name %>
 <%= f.text_field :name ,{:class=>'form-control'} %>

</div>
<div class="form-group">
 <%= f.label :email %>
 <%= f.text_field :email ,{:class=>'form-control'} %>

</div>
<div class="form-group">
 <%= f.label :password  %>
 <%= f.password_field :password ,{:class=>'form-control'} %>
 
</div>
<div class="form-group">
 <%= f.label :password_confirmation  %>
 <%= f.password_field :password_confirmation ,{:class=>'form-control'} %>
 
</div>
<%= submit_tag "Register",:class=>'form-control btn btn-primary' %>
<% end %>
</div>